### ISSUE TITLE
Code snippets are not shown on Chrome and Safari browsers in macOs

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/azure-docs.tr-tr#522]
Starting with the Recognize a phrase section code snippets are not available, only shown as [!code-csharp] without revealing the actual code

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: e4b55e56-55a1-d635-6bea-271dc361d676
* Version Independent ID: 8e9cb28f-c133-f310-3c7d-3a3b7e85f69d
* Content: [Hızlı başlangıç: bir mikrofon konuşma hizmetinden konuşmayı tanıma - Azure Cognitive Services](https://docs.microsoft.com/tr-tr/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-csharp#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/master/articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @cagrimunyas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @cagrimunyas, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47436. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
